"""Storage ports. Memory types implement these; they are not a product backend.

Production wiring is Postgres + ClickHouse + S3-compatible object storage.
There is no backend registry and no SQLite mode.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Protocol

from obsalt.domain.enums import EvalSlot, KeyScope
from obsalt.domain.models import AnalysisResult, CallRevision, EvalPolicy, EvalRunner, Rubric
from obsalt.plugin.types import ConnectionConfig, RawEnvelope, TombstoneHints


@dataclass(frozen=True)
class ApiKeyRecord:
    key_id: str
    org_id: str
    scopes: frozenset[KeyScope]


class ObjectStore(Protocol):
    def put(
        self, key: str, body: bytes, *, content_type: str = "application/octet-stream"
    ) -> None: ...
    def get(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...
    def list_keys(self, prefix: str = "") -> list[str]: ...
    def ensure_bucket(self) -> None: ...
    def ping(self) -> None: ...


class Inbox(Protocol):
    def accept(
        self,
        envelope: RawEnvelope,
        *,
        tombstone_hints: TombstoneHints,
    ) -> tuple[RawEnvelope, bool]:
        """Insert or resume the envelope, delivery-key dedupe, and outbox in one transaction."""

    def is_tombstoned(self, org_id: str, hints: TombstoneHints) -> bool: ...
    def tombstone(self, org_id: str, hints: TombstoneHints) -> None: ...
    def claim_outbox(self, limit: int = 32) -> list[RawEnvelope]: ...
    def outbox_depth(self) -> int: ...
    def mark_assembled(self, envelope_id: str) -> None: ...
    def mark_failed(self, envelope_id: str, error: str) -> None: ...
    def get_by_id(self, envelope_id: str) -> RawEnvelope | None: ...
    def list_envelopes(self, org_id: str | None = None) -> list[RawEnvelope]: ...
    def requeue(self, envelope_id: str) -> None: ...
    def drop_outbox(self, envelope_id: str) -> None: ...
    def list_dlq(self, limit: int = 200) -> list[dict[str, str]]: ...
    def purge_dlq(self, org_id: str, *, source_call_ids: set[str] | None = None) -> int: ...
    def record_run(
        self,
        *,
        org_id: str,
        envelope_id: str | None,
        decoder_version: str,
        status: str,
        error: str | None = None,
        run_id: str | None = None,
    ) -> str: ...


class ConnectionResolver(Protocol):
    def resolve(self, provider: str, ingest_key: str) -> ConnectionConfig | None: ...
    def add(self, cfg: ConnectionConfig, ingest_key: str) -> None: ...
    def delete(self, org_id: str, connection_id: str) -> bool: ...
    def list_for_org(self, org_id: str) -> list[ConnectionConfig]: ...


class RevisionPointerStore(Protocol):
    def compare_and_swap(
        self,
        org_id: str,
        call_id: str,
        expected: str | None,
        candidate: str,
        *,
        fact_frontier: frozenset[str],
    ) -> bool: ...
    def get(self, org_id: str, call_id: str) -> str | None: ...
    def list_org(self, org_id: str) -> list[tuple[str, str]]: ...
    def list_summaries(
        self,
        org_id: str,
        *,
        start: datetime | None = None,
        end: datetime | None = None,
        cursor: str | None = None,
        limit: int = 50,
        agent_id: str | None = None,
        source: str | None = None,
        outcome: str | None = None,
    ) -> tuple[list[dict[str, Any]], str | None] | None:
        """SQL summary page, or None when this adapter has no summary table."""

    def update_summary(self, revision: CallRevision) -> None: ...
    def delete(self, org_id: str, call_id: str) -> None: ...
    def frontier(self, org_id: str, call_id: str) -> frozenset[str]: ...


class RevisionSink(Protocol):
    def write(self, revision: CallRevision) -> None: ...
    def get(self, org_id: str, call_id: str, revision: str) -> CallRevision | None: ...
    def delete_call(self, org_id: str, call_id: str) -> None: ...
    def verify_visible(self, revision: CallRevision) -> CallRevision: ...
    def write_analysis(
        self, org_id: str, call_id: str, revision: str, results: list[AnalysisResult]
    ) -> None: ...
    def list_analysis(
        self,
        org_id: str,
        call_id: str | None = None,
        revision: str | None = None,
    ) -> list[AnalysisResult]: ...
    def list_for_call(self, org_id: str, call_id: str) -> list[CallRevision]: ...


class SearchIndex(Protocol):
    def upsert_revision(self, revision: CallRevision, *, index_version: str = "1") -> None: ...
    def query(
        self,
        org_id: str,
        q: str,
        *,
        limit: int = 20,
        filters: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def delete_for_call(self, org_id: str, call_id: str) -> None: ...


class RollupStore(Protocol):
    def contribute(self, revision: CallRevision) -> str: ...
    def delete_call(self, org_id: str, call_id: str) -> str: ...
    def rebuild(self, revisions: list[CallRevision]) -> str: ...
    def latency(self, org_id: str, as_of_generation: str) -> dict[str, Any]: ...


class HangupClusterStore(Protocol):
    def refresh(
        self,
        org_id: str,
        calls: Sequence[CallRevision],
        generation: str,
        *,
        embedder: Any | None = None,
        similarity_threshold: float = 0.3,
    ) -> dict[str, Any]: ...
    def get(self, org_id: str, generation: str | None = None) -> dict[str, Any] | None: ...


class GenerationStore(Protocol):
    def get(self, name: str = "fleet") -> str | None: ...
    def publish(self, name: str, generation: str, expected: str | None = None) -> bool: ...


class KeyDirectory(Protocol):
    def lookup(self, plaintext: str) -> ApiKeyRecord | None: ...
    def insert(
        self,
        org_id: str,
        plaintext: str,
        scopes: Iterable[KeyScope],
        *,
        expires_at: datetime | None = None,
    ) -> str: ...
    def revoke(self, key_id: str) -> None: ...
    def rotate(
        self,
        org_id: str,
        old_plaintext: str,
        new_plaintext: str,
        *,
        overlap_seconds: int = 86_400,
    ) -> str: ...


class RubricStore(Protocol):
    def list(self, org_id: str) -> list[Rubric]: ...
    def get(self, org_id: str, rubric_id: str) -> Rubric | None: ...
    def insert(self, rubric: Rubric) -> Rubric: ...
    def new_version(
        self,
        previous: Rubric,
        *,
        name: str | None = None,
        description: str | None = None,
        threshold: float | None = None,
        enabled: bool | None = None,
        kind: Any | None = None,
        spec: dict[str, Any] | None = None,
    ) -> Rubric: ...
    def delete(self, org_id: str, rubric_id: str) -> bool: ...


class EvalRunnerStore(Protocol):
    def list(self, org_id: str) -> list[EvalRunner]: ...
    def get(self, org_id: str, runner_id: str) -> EvalRunner | None: ...
    def get_slot(self, org_id: str, slot: EvalSlot | str) -> EvalRunner | None: ...
    def upsert(self, runner: EvalRunner) -> EvalRunner: ...
    def delete(self, org_id: str, runner_id: str) -> bool: ...
    def get_policy(self, org_id: str) -> EvalPolicy | None: ...
    def set_policy(self, policy: EvalPolicy) -> EvalPolicy: ...


class WebhookStore(Protocol):
    def list_destinations(self, org_id: str) -> list[dict[str, Any]]: ...
    def create(self, dest: dict[str, Any]) -> dict[str, Any]: ...
    def enqueue(self, item: dict[str, Any]) -> None: ...
    def claim(self, limit: int = 32) -> list[dict[str, Any]]: ...
    def mark_delivered(self, event_id: str) -> None: ...
    def mark_failed(self, event_id: str, detail: str, attempts: int) -> None: ...
    def purge_for_call(self, org_id: str, call_id: str) -> int: ...


class ReviewStore(Protocol):
    def insert(self, item: dict[str, Any]) -> dict[str, Any]: ...
    def list(self, org_id: str) -> list[dict[str, Any]]: ...


class DeletionStore(Protocol):
    def complete(
        self,
        org_id: str,
        *,
        call_ids: Any = None,
        source_call_id: str | None = None,
        caller_token: str | None = None,
    ) -> int: ...
    def backlog(self) -> int: ...


class OrgSpendStore(Protocol):
    def get(self, org_id: str, period: str | None = None) -> float: ...
    def add(self, org_id: str, amount: float, period: str | None = None) -> float: ...


class TraceAssembler(Protocol):
    def ingest(
        self,
        org_id: str,
        spans: list[Any],
        events: list[Any],
        *,
        now: datetime | None = None,
        mapper_name: str | None = None,
    ) -> Any: ...
    def due(
        self,
        *,
        now: datetime | None = None,
        grace_seconds: float = 0,
        max_call_duration_seconds: float = 4 * 60 * 60,
    ) -> list[Any]: ...
    def mark_finalized(self, record: Any, *, unrooted: bool = False) -> None: ...
    def ready(
        self,
        record: Any,
        *,
        now: datetime | None = None,
        grace_seconds: float = 0,
        max_call_duration_seconds: float = 4 * 60 * 60,
    ) -> bool: ...


class ForwardQueue(Protocol):
    def enqueue(self, job: Any) -> None: ...
    def claim(self, limit: int = 32) -> list[Any]: ...
    def requeue(self, job: Any) -> None: ...
    def mark_delivered(self, job: Any) -> None: ...
    def mark_failed_job(self, job: Any, detail: str) -> None: ...


class LeaseAccelerator(Protocol):
    def notify(self, envelope_id: str) -> None: ...
    def pop_ready(self, limit: int = 32) -> list[str]: ...
    def acquire(self, envelope_id: str, owner: str, ttl: int) -> bool: ...
    def release(self, envelope_id: str) -> None: ...
